name: craftown
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flame: ^1.14.0
  flame_tiled: ^1.18.3
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  flame_riverpod: ^5.1.5
  freezed: ^2.4.6
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  collection: ^1.18.0
  sembast: ^3.5.0+1
  path_provider: ^2.1.2
  path: ^1.8.3
  get_it: ^7.6.7
  intl: ^0.19.0
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  flame_audio: ^1.3.3
  sembast_web: ^2.2.0
  flutter_phoenix: ^1.1.1
  url_launcher: ^6.2.5
  desktop_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/audio/music/
    - assets/images/
    - assets/images/resources/
    - assets/images/tools/
    - assets/images/controller/
    - assets/images/farming/
    - assets/tiles/
    - assets/fonts/
    - assets/images/characters/Character10/
    - assets/images/characters/Character11/
    - assets/images/characters/Character03/
    - assets/images/characters/Character16/
    - assets/images/characters/Character18/
    - assets/images/characters/Character30/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    # - family: PixelifySans
    #   fonts:
    #     - asset: assets/fonts/PixelifySans-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/PixelifySans-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/PixelifySans-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/PixelifySans-Bold.ttf
    #       weight: 700
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
